//
// EBNF to be viewd at
//    (IPV6) https://www.bottlecaps.de/rr/ui
//    (IPV4) https://rr.red-dove.com/ui
//
// Copy and paste this at one of the urls shown above in the 'Edit Grammar' tab
// then click the 'View Diagram' tab.
//

MainProgram ::=
	shebang_opt StatementList

StatementList ::=
	Statement+

Statement ::=
	StatementBody
	| "const" Identifier Expression ';'
	| "var" Identifier type_opt var_assing_opt ';'
	| parseImport
	| "return" Expression ';'
	| "break" ';'
	| "continue" ';'
	| "delete" Expression ';'
	| "throw" Expression ';'
	| "try" StatementBody parseCatch_opt parseFinally_opt
	| "function" Identifier parseFunctionInto
	| parseStruct
	| "if" '(' Expression ')' StatementBody
	| "if" '(' Expression ')' StatementBody "else" StatementBody
	| parseSwitchCase
	| "loop" StatementBody
	| "while" '(' Expression ')' StatementBody
	| "do" ScopelessStatementBody "while" '(' Expression ')' ';'
	| "foreach" '(' Identifier (',' Identifier)* "in" Expression ')' ScopelessStatementBody
	| "for" '(' Statement Expression_opt ';' Expression ')' ScopelessStatementBody
	| Expression ';'

parseCatch_opt ::=
	/*empty*/
	| "catch" parseArgumentDefinitionList StatementBody

parseFinally_opt ::=
	/*empty*/
	| "finally" StatementBody
	| "finally" '(' Identifier ')' StatementBody

parseImport ::=
	"import"  importElement_oom ("from" readString)? ';'

importElement_oom ::=
	importElement
	| importElement_oom ',' importElement

importElement ::=
	Identifier '*'? (':' readNativeType)? ("as" Identifier)?

StatementBody ::=
	ScopelessStatementBody

ScopelessStatementBody ::=
	'{' StatementList '}'

parseFunctionInto ::=
	parseArgumentDefinitionList parseFunctionBody

parseArgumentDefinitionList ::=
	'(' argumentDefinition_zom ')' parseOptionalTyping

argumentDefinition_zom ::=
	/*empty*/
	| "..."
	| argumentDefinition_oom
	| argumentDefinition_oom ',' "..."

argumentDefinition_oom ::=
	argumentDefinition
	| argumentDefinition_zom ',' argumentDefinition

argumentDefinition ::=
	'_'
	| Identifier parseOptionalTyping assignExpression_opt

assignExpression_opt ::=
	'=' Expression

parseOptionalTyping ::=
	/*empty*/
	| parseTyping

parseTyping ::=
	':' BuiltinTypeName
	| ':' readNativeType
	| ':' readNativeType parseArrayTyping
	| ':' Identifier

parseFunctionBody ::=
	ScopelessStatementBody

parseStruct ::=
	"struct" Identifier '{' parseStructElements '}' ';'

parseStructElements ::=
	"static"? parseStructElement
	| parseStructElements "static"? parseStructElement

parseStructElement ::=
	"operator" '&' "this" '[' Identifier createParameterList parseOptionalTyping ']' ('=' Identifier createParameterList)?
	| "operator" '&' "this"  parseArgumentDefinitionList parseOptionalTyping ')'
	| "sizeof" "this"
	| "foreach" '(' Identifier ',' Identifier ')' "in" "this" createParameterList
	| "cast" '<' ("int"|"float"|"string") '>' "this"
	| Identifier "in" "this" createParameterList parseFunctionBody
	| Identifier
	| "constructor" parseFunction
	| "destructor" parseFunction
	| ("private"|"public"|"internal") ("get"|"set")? Identifier

parseSwitchCase ::=
	"switch" '(' Expression ')' '{' switchCaseElements '}'

switchCaseElements ::=
	"default" ':' Statement
	| switchCaseElement
	| switchCaseElements switchCaseElement

switchCaseElement ::=
	"case" switchCaseExpression (',' switchCaseExpression)* ':' Statement

switchCaseExpression ::=
	Expression
	| Expression ".." Expression

var_assing_opt ::=
	'='	Expression

Expression_opt ::=
	/*empty*/
	| Expression

Expression ::=
	"(" Expression ")"
	| UnaryPrefixExpression
	| UnarySuffixExpression
	| BinaryExpression
	| BuiltinConstant
	| Expression "." Identifier
	| Expression "!" Typename "(" ExpressionList ")"
	| Expression "[" Expression "]"
	| "type" "<" BuiltinTypeName ">"
	| "typeof" Expression
	| "sizeof" "var"
	| "sizeof" NativeTypeName
	| "sizeof" Expression
	| "as" "<" NativeTypeName ">" Expression
	| "as" "<" Expression ">" Expression
	| "cast" "<" "int" ">" Expression
	| "cast" "<" "float" ">" Expression
	| "cast" "<" "string" ">" Expression
	| "new" Expression "(" ExpressionList ")"
	| "new_stack" Expression "(" ExpressionList ")"
	| "map" // TODO
	| "map_stack" // TODO
	| "function" // TODO
	| "(" argumentDefinition ")" "->" parseFunctionBody // TODO allow expressions
	| "$"
	| "\'" . "\'"
	| "\"" .* "\""
	| "`" .* "`"
	| Identifier
	| NumberConstant

UnaryPrefixExpression ::=
	"typeof" Expression
	| "++" Expression
	| "--" Expression
	| "!" Expression
	| "~" Expression
	| "&" Expression
	| "*" Expression
	| "+" Expression
	| "-" Expression

UnarySuffixExpression ::=
	Expression "++"
	| Expression "--"

BinaryExpression ::=
	Expression ">>" Expression
	| Expression ">>" Expression
	| Expression "<<" Expression
	| Expression "===" Expression
	| Expression "!==" Expression
	| Expression "==" Expression
	| Expression "!=" Expression
	| Expression "<=" Expression
	| Expression ">=" Expression
	| Expression "<" Expression
	| Expression ">" Expression
	| Expression "=" Expression
	| Expression "+=" Expression
	| Expression "-=" Expression
	| Expression "*=" Expression
	| Expression "/=" Expression
	| Expression "%=" Expression
	| Expression ">>=" Expression
	| Expression "<<=" Expression
	| Expression "&=" Expression
	| Expression "^=" Expression
	| Expression "|=" Expression
	//| BinaryExpression "?" Expression // 2, true, &ptrs_ast_vtable_op_ternary},
	//| BinaryExpression ":" Expression //-1, true, &ptrs_ast_vtable_op_ternary},
	| Expression "?" Expression ":" Expression
	| Expression "instanceof" Expression
	| Expression "in" Expression
	| Expression "||" Expression
	| Expression "^^" Expression
	| Expression "&&" Expression
	| Expression "|" Expression
	| Expression "^" Expression
	| Expression "&" Expression
	| Expression "+" Expression
	| Expression "-" Expression
	| Expression "*" Expression
	| Expression "/" Expression
	| Expression "%" Expression

parseMap ::=
	"map_stack"
	| "map"

type_opt ::=
	':' readNativeType parseArrayTyping array_init_opt

array_init_opt ::=
	'=' '[' ExpressionList ']'

shebang_opt ::=
	"#!".*

comments ::=
	"//".*
	| "/*".*?"*/"

BuiltinConstant ::=
	"true"
	| "false"
	| "null"
	| "undefined"
	| "NaN"
	| "Infinity"
	| "PI"
	| "E"

BuiltinTypeName ::=
	"undefined"
	| "int"
	| "float"
	| "pointer"
	| "struct"
	| "function"

readNativeType ::=

Identifier ::=
	[a-zA-Z_][a-zA-Z0-9_]*

NumberConstant ::=
	[-]?[0-9]+((e|.)[0-9]+)?
